version: '3.7'
services:
  php:
    build: .
    container_name: php
    expose:
      - "9000"
    volumes:
      -  ./www/:/var/www/html/
    working_dir: /var/www/html/
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/html/
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php:php5.6-fpm

